# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HB网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HB网易新闻

pod 'AFNetworking'
pod 'SDWebImage'

end
